apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: delivery-demo-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: delivery-platform
  source:
    repoURL: https://github.com/L3xcy/kubernetes-gitops-delivery-platform.git
    targetRevision: main
    path: charts/delivery-demo
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: delivery-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
